[webserver]
port = ":9090"

# register data providers
[[providers]]
name = "test_postgis"
type = "postgis"
host = "localhost"
port = 5432
database = "gdey" 
user = "gdey"
password = ""

# maps are made up of layers
[[maps]]
name = "zoning"					# used in the URL to reference this map

	[[maps.layers]]
	name = "landuse" 			# will be encoded as the layer name in the tile
	provider = "test_postgis"	# must match a data provider
	minzoom = 12
	maxzoom = 20
	sql = "gis.zoning_base_3857"
