[webserver]
port = ":8080"

# register data providers
[[providers]]
name = "test_postgis"
type = "postgis"
host = "localhost"
port = 5432
database = "ARolek" 
user = "ARolek"
password = ""

    [[providers.layers]]
    name = "landuse"                    # will be encoded as the layer name in the tile
    table_name = "gis.zoning_base_3857" # sql or table_name are required
    geom_field = "wkb_geom"             # geom field. default is geom
    gid_field = "fid"                   # geom id field. default is gid


# maps are made up of layers
[[maps]]
name = "zoning"							# used in the URL to reference this map (/maps/:map_name)

	[[maps.layers]]
	provider_layer = "test_postgis.landuse"	# must match a data provider query
	minzoom = 12
	maxzoom = 16

		[[maps.layers.default_tags]]	# a table of default tags to encode in the tile. SQL statements will override
		cls = "park"