[webserver]
port = ":8080"

# register data providers
[[providers]]
name = "test_postgis"
type = "postgis"
host = "localhost"
port = 5432
database = "ARolek" 
user = "ARolek"
password = ""

# maps are made up of layers
[[maps]]
name = "zoning"
layer = "landuse"

# layers define data providers
[[layers]]
name = "landuse"
provider = "test_postgis"
table_name = "gis.zoning_base_3857"
sql = "gis.zoning_base_3857"
