[webserver]
port = ":8080"

# register data providers
[[providers]]
name = "test_postgis"
type = "postgis"
host = "host"
port = 5432
database = "ARolek" 
user = "ARolek"
password = ""

# maps are made up of layers
[[maps]]
name = "zoning"
minZoom = 0
maxZoom = 18
layer = "sd_zoning"

# layers define data providers
[[layers]]
name = "sd_zoning"
provider = "test_postgis"
table_name = "gis.zoning_base_3857"
geometry_field = "geom"
fid_field = "gid"