[server]
port = ":8080"

# register data providers
[providers]

	[providers.test_postgis]
	type = "postgis"
	host = "host"
	port = 5432
	database = "database" 
	user = "user"
	password = "password"

# maps are made up of layers
[maps]

	[maps.rio]

		[maps.rio.rio_buildings]
		minZoom = 0
		maxZoom = 18

# layers define data providers
[layers]
	
	[layers.rio_buildings]
	provider = "test_postgis"
	config = "sql statement"